name: stack-regression-tests
on:
  pull_request:
    branches:
      - main
jobs:
   stack-tests:
     runs-on: ubuntu-latest
     steps:
     
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.17.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=registry --addons=ingress --insecure-registry "10.0.0.0/24"' 
    
      - name: Wait for nodes to be ready
        run: |
          while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do 
          echo "waiting for nodes" && sleep 1; 
          done
    
      - name: Install odo
        run: | 
         sudo curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o /usr/local/bin/odo
         sudo chmod +x /usr/local/bin/odo
    
      - name: Print version info
        run: |
         set -x
         docker version
         kubectl version
         odo version
         minikube version
         set +x
        
      - name: Build stack
        run: ./test/utils.sh buildStack
        
      - name: Build stack image
        run: ./test/utils.sh buildStackImage

      - name: Devfile regression
        run: ./test/devfile-regression.sh

      - name: Inner loop test
        run: ./test/inner-loop-test.sh

      - name: Inner loop parent plugin test
        run: ./test/inner-loop-parent-plugin-test.sh

      - name: Outer loop test
        run: ./test/outer-loop-test.sh
